In [36]:
import pandas as pd
import numpy as np

**Задание 1**. Используя библиотеку Numpy, выполните следующие действия:

1.   Создайте квадратную матрицу размера 5х5, заполненную единицами.
2.   Создайте одномерный массив длины 20, заполненный случайными элементами.
3.   Преобразуйте массив из предыдущего пункта в двумерный с размерностью 4 на 5.

In [37]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
arr = np.random.random(size=20)*100
arr

array([19.42315932, 83.6107784 , 91.52809546, 69.26379344, 21.93328872,
       27.76608296, 21.96875256, 37.06304312, 40.37342343, 65.7042952 ,
       95.92725821, 56.66712881, 29.20534423, 58.47161031,  7.69950061,
       42.79946671, 63.09855844, 23.48326354, 56.12943591, 63.48657199])

In [39]:
reshaped_arr = arr.reshape(4, 5)
reshaped_arr

array([[19.42315932, 83.6107784 , 91.52809546, 69.26379344, 21.93328872],
       [27.76608296, 21.96875256, 37.06304312, 40.37342343, 65.7042952 ],
       [95.92725821, 56.66712881, 29.20534423, 58.47161031,  7.69950061],
       [42.79946671, 63.09855844, 23.48326354, 56.12943591, 63.48657199]])

**Задание 2.** Создайте двумерный массив размерности `n*m` (`n` и `m` вводятся с клавиатуры) и заполните его случайными значениями. Найдите в этом массиве:

1. Все элементы, большие некоторого числа `k` (вводится с клавиатуры).
2. Статистические характеристики элементов массива (математическое ожидание, дисперсию, среднее квадратичное отклонение).
3. Минимальный и максимальный элементы массива.

In [40]:
n = int(input("Input number of rows: "))
m = int(input("Input number of columns: "))

arr = np.random.random(size=(n, m)) * 100
arr

array([[38.1605721 , 15.75564063,  5.13404231, 74.52616265, 57.24229345,
        91.23286084],
       [10.86631904, 63.72535266, 87.73294348, 91.17734979, 61.71812886,
        49.01604448],
       [89.65156384,  7.44654489, 72.99618036, 64.46746674, 21.23871952,
         9.62543199],
       [79.35348805, 82.45631545, 17.53691208, 77.06737782, 21.85062011,
        21.29367677],
       [93.98751578, 22.10484695, 36.73615073, 46.11361706, 96.39122374,
         7.04515612]])

In [41]:
k = int(input("Input number: "))
arr[arr > k]

array([38.1605721 , 74.52616265, 57.24229345, 91.23286084, 63.72535266,
       87.73294348, 91.17734979, 61.71812886, 49.01604448, 89.65156384,
       72.99618036, 64.46746674, 79.35348805, 82.45631545, 77.06737782,
       93.98751578, 36.73615073, 46.11361706, 96.39122374])

In [42]:
print('Общее мат. ожидание: ', arr.mean())
print('Мат. ожидание по столбцам: ', arr.mean(axis=0))
print('Мат. ожидание по строкам: ', arr.mean(axis=1))
print('Общая дисперсия: ', arr.var())
print('Дисперсия по столбцам: ', arr.var(axis=0))
print('Дисперсия по строкам: ', arr.var(axis=1))
print('Общее стандартное отклонение: ', arr.std())
print('Стандартное отклонение по столбцам: ', arr.std(axis=0))
print('Стандартное отклонение по строкам: ', arr.std(axis=1))

Общее мат. ожидание:  50.45501727630013
Мат. ожидание по столбцам:  [62.40389176 38.29774012 44.02724579 70.67039481 51.68819713 35.64263404]
Мат. ожидание по строкам:  [47.00859533 60.70602305 44.23765122 49.92639838 50.3964184 ]
Общая дисперсия:  981.6330615463252
Дисперсия по столбцам:  [1054.22194098  863.73910798 1003.3932609   223.56703798  789.45195872
  993.94490852]
Дисперсия по строкам:  [ 937.7072718   714.95809761 1063.21066298  886.3237951  1150.06602423]
Общее стандартное отклонение:  31.331023946662278
Стандартное отклонение по столбцам:  [32.4687841  29.38943871 31.67638333 14.9521583  28.09718774 31.52689183]
Стандартное отклонение по строкам:  [30.62200633 26.73870037 32.60691128 29.77119069 33.91262338]

In [43]:
print(arr.min())
print(arr.max())

5.134042311799536
96.39122373875746

**Задание 3** Даны два вектора одинакового размера. Найдите:

*  Косинус угла между векторами.
*  Евклидово расстояние между векторами.

In [44]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cosinus = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosinus

np.float64(0.9746318461970762)

In [45]:
euclidean = np.linalg.norm(a - b)
euclidean

np.float64(5.196152422706632)

**Задание 4.** Постройте таблицу значений функции `y = x*x - x + 2` на интервале `[-10, 10]` c шагом `0.5`

In [46]:
x = np.arange(-10, 10.5, 0.5)
y = x*x - x + 2

df = pd.DataFrame({'x': x, 'y': y})
df

       x       y
0  -10.0  112.00
1   -9.5  101.75
2   -9.0   92.00
3   -8.5   82.75
4   -8.0   74.00
5   -7.5   65.75
6   -7.0   58.00
7   -6.5   50.75
8   -6.0   44.00
9   -5.5   37.75
10  -5.0   32.00
11  -4.5   26.75
12  -4.0   22.00
13  -3.5   17.75
14  -3.0   14.00
15  -2.5   10.75
16  -2.0    8.00
17  -1.5    5.75
18  -1.0    4.00
19  -0.5    2.75
20   0.0    2.00
21   0.5    1.75
22   1.0    2.00
23   1.5    2.75
24   2.0    4.00
25   2.5    5.75
26   3.0    8.00
27   3.5   10.75
28   4.0   14.00
29   4.5   17.75
30   5.0   22.00
31   5.5   26.75
32   6.0   32.00
33   6.5   37.75
34   7.0   44.00
35   7.5   50.75
36   8.0   58.00
37   8.5   65.75
38   9.0   74.00
39   9.5   82.75
40  10.0   92.00

**Задание 5**. Выполните следующие действия:
1.  Загрузите данные из файла `sp500.csv` в датафрейм. Чтобы убедиться, что загрузка прошла корректно, выведите на экран первые 10 строк данных.
2.  Измените команду для открытия файла таким образом, чтобы загружались только столбцы Symbol, Name, Sector, Price, Book Value, 52 week low, 52 week high, Market Cap. Столбец Symbol при этом должен быть индексным. Убедитесь, что данные загружены корректно.
3.  Выведите значения столбца Name.
4.  Выведите строку с индексом NFLX.
5.  Выведите строку с номером 238.

In [47]:
sp500 = pd.read_csv("lab1/sp500.csv", sep =',')
sp500.head(10)

,Symbol,Name,Sector,Price,Dividend Yield,Price/Earnings,Earnings/Share,Book Value,52 week low,52 week high,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,3M Co.,Industrials,141.14,2.12,20.33,6.900,26.668,107.15,143.37,92.345,8.1210,2.95,5.26,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=MMM
1,ABT,Abbott Laboratories,Health Care,39.60,1.82,25.93,1.529,15.573,32.70,40.49,59.477,4.3590,2.74,2.55,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=ABT
2,ABBV,AbbVie Inc.,Health Care,53.95,3.02,20.87,2.570,2.954,40.10,54.78,85.784,7.1900,4.48,18.16,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=ABBV
3,ACN,Accenture,Information Technology,79.79,2.34,19.53,4.068,8.326,69.00,85.88,50.513,4.4230,1.75,9.54,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=ACN
4,ACE,ACE Limited,Financials,102.91,2.21,10.00,10.293,86.897,84.73,104.07,34.753,4.2750,1.79,1.18,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=ACE
5,ACT,Actavis Inc,Health Care,213.77,NaN,NaN,-3.597,55.188,118.68,230.77,37.291,2.4770,3.93,3.85,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=ACT
6,ADBE,Adobe Systems Inc,Information Technology,64.30,NaN,121.44,0.520,13.262,41.91,71.11,32.004,0.7525,7.77,4.76,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=ADBE
7,AES,AES Corp,Utilities,13.61,1.32,NaN,-0.040,5.781,11.17,15.54,9.872,4.2910,0.62,2.37,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=AES
8,AET,Aetna Inc,Health Care,76.39,1.13,13.29,5.681,40.021,57.72,76.71,27.302,4.7370,0.52,1.89,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=AET
9,AFL,AFLAC Inc,Financials,61.31,2.36,9.58,6.459,34.527,54.02,67.62,27.844,4.7130,1.21,1.79,http://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=AFL

In [48]:
sp500 = pd.read_csv("lab1/sp500.csv", sep =',',
                    usecols=['Symbol', 'Name', 'Sector', 'Price', 'Book Value', '52 week low', '52 week high', 'Market Cap'],
                    index_col='Symbol')
sp500.head()

,Name,Sector,Price,Book Value,52 week low,52 week high,Market Cap
Symbol,,,,,,,
MMM,3M Co.,Industrials,141.14,26.668,107.15,143.37,92.345
ABT,Abbott Laboratories,Health Care,39.60,15.573,32.70,40.49,59.477
ABBV,AbbVie Inc.,Health Care,53.95,2.954,40.10,54.78,85.784
ACN,Accenture,Information Technology,79.79,8.326,69.00,85.88,50.513
ACE,ACE Limited,Financials,102.91,86.897,84.73,104.07,34.753

In [49]:
sp500['Name'].head()

Symbol
MMM                  3M Co.
ABT     Abbott Laboratories
ABBV            AbbVie Inc.
ACN               Accenture
ACE             ACE Limited
Name: Name, dtype: object

In [50]:
sp500.loc['NFLX']

Name                      NetFlix Inc.
Sector          Information Technology
Price                           402.35
Book Value                      24.664
52 week low                     205.75
52 week high                     458.0
Market Cap                      24.117
Name: NFLX, dtype: object

In [51]:
sp500.iloc[238]

Name            International Flav/Frag
Sector                        Materials
Price                             98.86
Book Value                       18.671
52 week low                       73.02
52 week high                     100.93
Market Cap                        8.036
Name: IFF, dtype: object

**Задание 6.** Загрузите из файла `sp500.csv` данные в датафрейм, выбрав столбцы Symbol, Name, Sector, Price, Book Value, 52 week low, 52 week high, Market Cap. Столбец Symbol при этом должен быть индексным. Выполните следующие задания:

1.  Выведите строки с 100 по 120.
2.  Создайте копию датафрейма и удалите значения столбца Book Value из копии.
3.  Выберите все строки, в которых значение столбца `52 week low < 80`.
4.  Выберите строки, где `Sector` имеет значение `Financials` или `Energy`
5.  (Базовый уровень). Выберите только те строки, где `Sector` имеет значение `Financials` или `Energy`, и при этом наименьшая цена за год превышает 50.

In [52]:
sp500.iloc[100:121]

,Name,Sector,Price,Book Value,52 week low,52 week high,Market Cap
Symbol,,,,,,,
CSCO,Cisco Systems,Information Technology,24.52,10.904,20.22,26.49,125.600
C,Citigroup Inc.,Financials,47.29,66.247,45.06,55.28,143.700
CTXS,Citrix Systems,Information Technology,61.44,18.490,51.18,77.16,10.068
CLF,Cliffs Natural Resources,Materials,16.34,34.523,15.41,28.98,2.503
CLX,Clorox Co.,Consumer Staples,88.33,0.412,80.20,96.76,11.358
CME,CME Group Inc.,Financials,71.00,63.784,63.10,84.71,23.841
CMS,CMS Energy,Utilities,29.30,13.480,25.74,30.53,7.864
COH,Coach Inc.,Consumer Discretionary,41.53,8.715,41.13,59.58,11.386
KO,Coca Cola Co.,Consumer Staples,40.58,7.435,36.83,43.05,178.400
CCE,Coca-Cola Enterprises,Consumer Staples,45.85,8.169,33.81,48.04,11.528
CTSH,Cognizant Technology Solutions,Information Technology,48.62,10.885,30.46,54.00,29.583
CL,Colgate-Palmolive,Consumer Staples,66.73,1.781,55.47,67.95,61.084
CMCSA,Comcast Corp.,Consumer Discretionary,51.97,19.720,38.75,55.28,135.100
CMA,Comerica Inc.,Financials,46.81,40.083,37.00,53.50,8.504
CSC,Computer Sciences Corp.,Information Technology,61.64,27.093,42.54,64.72,8.973
CAG,ConAgra Foods Inc.,Consumer Staples,31.61,13.360,28.09,37.28,13.313
COP,ConocoPhillips,Energy,78.43,43.351,58.71,78.82,96.289
CNX,CONSOL Energy Inc.,Energy,44.43,22.157,26.25,45.57,10.215
ED,Consolidated Edison,Utilities,54.13,42.421,52.23,60.85,15.854
STZ,Constellation Brands,Consumer Staples,82.51,26.016,49.09,85.91,15.825
GLW,Corning Inc.,Industrials,21.33,14.816,13.82,21.77,27.910

In [53]:
sp500_copy = sp500.copy()
del sp500_copy['Book Value']
sp500_copy

,Name,Sector,Price,52 week low,52 week high,Market Cap
Symbol,,,,,,
MMM,3M Co.,Industrials,141.14,107.15,143.37,92.345
ABT,Abbott Laboratories,Health Care,39.60,32.70,40.49,59.477
ABBV,AbbVie Inc.,Health Care,53.95,40.10,54.78,85.784
ACN,Accenture,Information Technology,79.79,69.00,85.88,50.513
ACE,ACE Limited,Financials,102.91,84.73,104.07,34.753
...,...,...,...,...,...,...
YHOO,Yahoo Inc.,Information Technology,35.02,23.82,41.72,35.258
YUM,Yum! Brands Inc,Consumer Discretionary,74.77,64.08,79.70,33.002
ZMH,Zimmer Holdings,Health Care,101.84,74.55,108.33,17.091
ZION,Zions Bancorp,Financials,28.43,26.39,33.33,5.257
ZTS,Zoetis Inc,Health Care,30.53,28.14,34.28,15.296

In [54]:
sp1 = sp500[sp500['52 week low'] < 80]
sp1.head()

,Name,Sector,Price,Book Value,52 week low,52 week high,Market Cap
Symbol,,,,,,,
ABT,Abbott Laboratories,Health Care,39.60,15.573,32.70,40.49,59.477
ABBV,AbbVie Inc.,Health Care,53.95,2.954,40.10,54.78,85.784
ACN,Accenture,Information Technology,79.79,8.326,69.00,85.88,50.513
ADBE,Adobe Systems Inc,Information Technology,64.30,13.262,41.91,71.11,32.004
AES,AES Corp,Utilities,13.61,5.781,11.17,15.54,9.872

In [55]:
sp2 = sp500[(sp500.Sector == 'Financials') | (sp500.Sector == 'Energy')]
sp2.head()

,Name,Sector,Price,Book Value,52 week low,52 week high,Market Cap
Symbol,,,,,,,
ACE,ACE Limited,Financials,102.91,86.897,84.73,104.07,34.753
AFL,AFLAC Inc,Financials,61.31,34.527,54.02,67.62,27.844
ALL,Allstate Corp,Financials,58.38,47.465,45.60,58.69,25.336
AXP,American Express Co,Financials,88.78,18.846,71.47,94.35,94.107
AIG,American Intl Group Inc,Financials,53.60,71.775,41.53,54.03,77.540

In [56]:
sp3 = sp500[((sp500.Sector == 'Financials') | (sp500.Sector == 'Energy')) & (sp500['52 week low'] > 50)]
sp3.head()

,Name,Sector,Price,Book Value,52 week low,52 week high,Market Cap
Symbol,,,,,,,
ACE,ACE Limited,Financials,102.91,86.897,84.73,104.07,34.753
AFL,AFLAC Inc,Financials,61.31,34.527,54.02,67.62,27.844
AXP,American Express Co,Financials,88.78,18.846,71.47,94.35,94.107
AMT,American Tower Corp A,Financials,88.41,9.279,67.89,90.00,34.988
AMP,Ameriprise Financial,Financials,110.93,43.786,76.77,116.82,21.063

**Задание 7** Загрузите файл `tips.csv`. Рассчитайте все одномерные статистические характеристики по столбцу `tip`.

**Указание:** см.  файл `4 Math.ipynb`

In [57]:
tips = pd.read_csv("lab1/tips.csv", sep =',')
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [59]:
print('Математическое ожидание', tips.tip.mean())
print('Дисперсия', tips.tip.var())
print('Ст. отклонение', tips.tip.std())
print('Минимум', tips.tip.min())
print('Максимум', tips.tip.max())
print('Сумма', tips.tip.sum())
print('Медиана', tips.tip.median())
print('Мода (самое частое значение)', tips.tip.mode())
print('Счетчик', tips.tip.count())
print('Квантиль (25%)', tips.tip.quantile(0.25))

Математическое ожидание 2.99827868852459
Дисперсия 1.914454638062471
Ст. отклонение 1.3836381890011822
Минимум 1.0
Максимум 10.0
Сумма 731.5799999999999
Медиана 2.9
Мода (самое частое значение) 0    2.0
Name: tip, dtype: float64
Счетчик 244
Квантиль (25%) 2.0